import type { Brand, Car, Category, Customer, Enquiry, TestDrive } from '@/types';

export const BRANDS: Brand[] = [
  { id: 'maruti', name: 'Maruti Suzuki', logo: '', count: 14 },
  { id: 'hyundai', name: 'Hyundai', logo: '', count: 11 },
  { id: 'tata', name: 'Tata', logo: '', count: 9 },
  { id: 'mahindra', name: 'Mahindra', logo: '', count: 8 },
  { id: 'toyota', name: 'Toyota', logo: '', count: 7 },
  { id: 'kia', name: 'Kia', logo: '', count: 6 },
  { id: 'bmw', name: 'BMW', logo: '', count: 5 },
  { id: 'mercedes', name: 'Mercedes-Benz', logo: '', count: 5 },
  { id: 'audi', name: 'Audi', logo: '', count: 4 },
  { id: 'volkswagen', name: 'Volkswagen', logo: '', count: 4 },
];

export const CATEGORIES: Category[] = [
  { id: 'suv', name: 'SUV', description: 'Spacious, powerful and ready for any terrain', image: 'https://images.pexels.com/photos/16646417/pexels-photo-16646417.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', count: 18 },
  { id: 'sedan', name: 'Sedan', description: 'Refined comfort for the daily drive', image: 'https://images.pexels.com/photos/12122221/pexels-photo-12122221.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', count: 12 },
  { id: 'hatchback', name: 'Hatchback', description: 'Compact and city-friendly', image: 'https://images.pexels.com/photos/17078606/pexels-photo-17078606.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', count: 14 },
  { id: 'muv', name: 'MUV', description: 'Room for the whole family', image: 'https://images.pexels.com/photos/4909544/pexels-photo-4909544.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', count: 8 },
  { id: 'luxury', name: 'Luxury', description: 'Statement-making premium rides', image: 'https://images.pexels.com/photos/28380935/pexels-photo-28380935.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', count: 9 },
  { id: 'electric', name: 'Electric', description: 'Silent, smart and zero-emission', image: 'https://images.pexels.com/photos/28851165/pexels-photo-28851165.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', count: 7 },
];

const GALLERY = [
  'https://images.pexels.com/photos/27692895/pexels-photo-27692895.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'https://images.pexels.com/photos/19477337/pexels-photo-19477337.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'https://images.pexels.com/photos/3076827/pexels-photo-3076827.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
];

const reviewBank = [
  { author: 'Rahul Mehta', rating: 5, title: 'Fantastic buying experience', body: 'Auto Empire made the whole process smooth. The test drive was well organised and the team was knowledgeable.' },
  { author: 'Priya Sharma', rating: 4, title: 'Great value for money', body: 'Compared three cars side by side and picked the right one. The compare feature is genuinely useful.' },
  { author: 'Aman Verma', rating: 5, title: 'Smooth and premium', body: 'Loved the showroom feel of the website. Found my dream car within my budget.' },
  { author: 'Sneha Iyer', rating: 4, title: 'Helpful filters', body: 'The filters saved me hours. Narrowed down to exactly the body type and fuel I wanted.' },
  { author: 'Vikram Nair', rating: 5, title: 'Best car portal', body: 'Detailed specs and honest pros and cons. Exactly what a buyer needs before visiting a dealership.' },
];

function makeReviews(seed: number) {
  return [0, 1, 2].map((i) => {
    const r = reviewBank[(seed + i) % reviewBank.length];
    return {
      id: `r-${seed}-${i}`,
      author: r.author,
      rating: r.rating,
      date: ['2025-07-12', '2025-06-28', '2025-05-04'][i],
      title: r.title,
      body: r.body,
    };
  });
}

type CarSeed = Omit<Car, 'reviews' | 'gallery'> & { gallery?: string[] };

function buildCar(seed: CarSeed, idx: number): Car {
  return {
    ...seed,
    gallery: seed.gallery ?? [seed.image, ...GALLERY],
    reviews: makeReviews(idx),
  };
}

const seeds: CarSeed[] = [
  {
    id: 'maruti-swift',
    brand: 'Maruti Suzuki', model: 'Swift', variant: 'ZXi+', year: 2025,
    price: 745000, emiStart: 12400, fuel: 'Petrol', transmission: 'Manual', bodyType: 'Hatchback',
    mileage: '24.8 kmpl', seating: 5, bootSpace: '265 L', engine: '1197 cc', power: '89 bhp', torque: '113 Nm', safetyRating: 4,
    status: 'New', featured: true, published: true,
    image: 'https://images.pexels.com/photos/17078606/pexels-photo-17078606.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Pearl Arctic White', hex: '#f4f4f4' }, { name: 'Magma Red', hex: '#b81515' }, { name: 'Midnight Blue', hex: '#1e2a4a' }],
    features: ['7-inch SmartPlay Studio', 'Apple CarPlay & Android Auto', '6 airbags', 'ABS with EBD', 'Reverse camera', 'Keyless entry'],
    pros: ['Class-leading fuel economy', 'Peppy engine', 'Agile handling'],
    cons: ['Boot space could be larger', 'No diesel option'],
    variants: [
      { name: 'LXi', price: 649000, transmission: 'Manual', fuel: 'Petrol' },
      { name: 'VXi', price: 699000, transmission: 'Manual', fuel: 'Petrol' },
      { name: 'ZXi+', price: 745000, transmission: 'Manual', fuel: 'Petrol' },
    ],
    description: 'The Maruti Suzuki Swift is India\'s favourite hatchback, blending sporty design with exceptional fuel efficiency and everyday practicality.',
  },
  {
    id: 'maruti-brezza',
    brand: 'Maruti Suzuki', model: 'Brezza', variant: 'ZDi+', year: 2025,
    price: 1189000, emiStart: 19800, fuel: 'Diesel', transmission: 'Manual', bodyType: 'SUV',
    mileage: '19.8 kmpl', seating: 5, bootSpace: '328 L', engine: '1462 cc', power: '103 bhp', torque: '138 Nm', safetyRating: 4,
    status: 'New', featured: false, published: true,
    image: 'https://images.pexels.com/photos/4909544/pexels-photo-4909544.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Granite White', hex: '#eee' }, { name: 'Sizzling Red', hex: '#dc1f1f' }, { name: 'Blazing Blue', hex: '#1e3a5f' }],
    features: ['9-inch SmartPlay Pro+', '360-degree camera', '6 airbags', 'Wireless charging', 'Sunroof', 'Heads-up display'],
    pros: ['Refined diesel engine', 'Bold SUV stance', 'Feature-rich cabin'],
    cons: ['No automatic on diesel', 'Firm ride at low speeds'],
    variants: [
      { name: 'LDi', price: 999000, transmission: 'Manual', fuel: 'Diesel' },
      { name: 'VDi', price: 1089000, transmission: 'Manual', fuel: 'Diesel' },
      { name: 'ZDi+', price: 1189000, transmission: 'Manual', fuel: 'Diesel' },
    ],
    description: 'The Maruti Suzuki Brezza is a compact SUV that brings bold design, a commanding driving position and a frugal diesel engine to the urban commute.',
  },
  {
    id: 'hyundai-creta',
    brand: 'Hyundai', model: 'Creta', variant: 'SX(O) Turbo', year: 2025,
    price: 1599000, emiStart: 26600, fuel: 'Petrol', transmission: 'DCT', bodyType: 'SUV',
    mileage: '17.4 kmpl', seating: 5, bootSpace: '433 L', engine: '1482 cc', power: '138 bhp', torque: '242 Nm', safetyRating: 5,
    status: 'New', featured: true, published: true,
    image: 'https://images.pexels.com/photos/14696345/pexels-photo-14696345.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Atlas White', hex: '#f4f4f4' }, { name: 'Phantom Black', hex: '#0d0d10' }, { name: 'Titan Grey', hex: '#4a4a53' }],
    features: ['10.25-inch touchscreen', 'Bose premium audio', 'Panoramic sunroof', 'Level 2 ADAS', 'Ventilated seats', '8 airbags'],
    pros: ['Premium interior', 'Powerful turbo engine', 'Loaded with features'],
    cons: ['Pricey top variant', 'DCT can hesitate in traffic'],
    variants: [
      { name: 'EX', price: 1099000, transmission: 'Manual', fuel: 'Petrol' },
      { name: 'SX', price: 1299000, transmission: 'Manual', fuel: 'Petrol' },
      { name: 'SX(O) Turbo', price: 1599000, transmission: 'DCT', fuel: 'Petrol' },
    ],
    description: 'The Hyundai Creta redefines the mid-size SUV segment with a bold stance, turbocharged performance and a cabin packed with segment-first features.',
  },
  {
    id: 'hyundai-i20',
    brand: 'Hyundai', model: 'i20', variant: 'Asta(O) Turbo', year: 2025,
    price: 1149000, emiStart: 19100, fuel: 'Petrol', transmission: 'DCT', bodyType: 'Hatchback',
    mileage: '20.0 kmpl', seating: 5, bootSpace: '311 L', engine: '998 cc', power: '118 bhp', torque: '172 Nm', safetyRating: 5,
    status: 'New', featured: false, published: true,
    image: 'https://images.pexels.com/photos/20475072/pexels-photo-20475072.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Polar White', hex: '#f4f4f4' }, { name: 'Phantom Black', hex: '#0d0d10' }, { name: 'Fiery Red', hex: '#dc1f1f' }],
    features: ['10.25-inch cluster', 'Bose sound system', '6 airbags', 'Tyre pressure monitor', 'Wireless CarPlay', 'Sunroof'],
    pros: ['Premium hatchback feel', 'Refined turbo engine', 'Feature-rich'],
    cons: ['Low ground clearance', 'Pricier than rivals'],
    variants: [
      { name: 'Magna', price: 749000, transmission: 'Manual', fuel: 'Petrol' },
      { name: 'Sportz', price: 899000, transmission: 'Manual', fuel: 'Petrol' },
      { name: 'Asta(O) Turbo', price: 1149000, transmission: 'DCT', fuel: 'Petrol' },
    ],
    description: 'The Hyundai i20 is a premium hatchback that combines European design cues with a feature-packed cabin and punchy turbo performance.',
  },
  {
    id: 'tata-nexon',
    brand: 'Tata', model: 'Nexon', variant: 'Fearless+ S', year: 2025,
    price: 1499000, emiStart: 24900, fuel: 'Petrol', transmission: 'AMT', bodyType: 'SUV',
    mileage: '17.0 kmpl', seating: 5, bootSpace: '382 L', engine: '1199 cc', power: '118 bhp', torque: '170 Nm', safetyRating: 5,
    status: 'New', featured: true, published: true,
    image: 'https://images.pexels.com/photos/14463716/pexels-photo-14463716.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Pure White', hex: '#f4f4f4' }, { name: 'Opera Blue', hex: '#1e3a5f' }, { name: 'Calgary White', hex: '#eee' }],
    features: ['10.25-inch infotainment', 'JBL sound system', '6 airbags', 'Wireless charger', 'Sunroof', 'Drive modes'],
    pros: ['5-star safety rating', 'Spacious cabin', 'Refined engines'],
    cons: ['AMT can be jerky', 'Infotainment laggy at times'],
    variants: [
      { name: 'Smart', price: 849000, transmission: 'Manual', fuel: 'Petrol' },
      { name: 'Creative', price: 1099000, transmission: 'Manual', fuel: 'Petrol' },
      { name: 'Fearless+ S', price: 1499000, transmission: 'AMT', fuel: 'Petrol' },
    ],
    description: 'The Tata Nexon is India\'s safest compact SUV with a 5-star rating, bold design and a choice of refined petrol, diesel and electric powertrains.',
  },
  {
    id: 'tata-nexon-ev',
    brand: 'Tata', model: 'Nexon EV', variant: 'Empowered+ LR', year: 2025,
    price: 1999000, emiStart: 33200, fuel: 'Electric', transmission: 'Automatic', bodyType: 'Electric',
    mileage: '465 km range', seating: 5, bootSpace: '350 L', engine: 'Permanent Magnet AC', power: '143 bhp', torque: '215 Nm', safetyRating: 5,
    status: 'New', featured: true, published: true,
    image: 'https://images.pexels.com/photos/28851165/pexels-photo-28851165.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Intelligent White', hex: '#f4f4f4' }, { name: 'Phantom Black', hex: '#0d0d10' }, { name: 'Voltage Blue', hex: '#1e3a5f' }],
    features: ['12.3-inch touchscreen', 'ARCade infotainment', 'Fast charging', '6 airbags', 'Ventilated seats', 'Wireless CarPlay'],
    pros: ['Class-leading range', 'Silent drive', 'Quick charging'],
    cons: ['Charging infrastructure still growing', 'Premium pricing'],
    variants: [
      { name: 'Creative', price: 1399000, transmission: 'Automatic', fuel: 'Electric' },
      { name: 'Empowered', price: 1699000, transmission: 'Automatic', fuel: 'Electric' },
      { name: 'Empowered+ LR', price: 1999000, transmission: 'Automatic', fuel: 'Electric' },
    ],
    description: 'The Tata Nexon EV brings electric mobility to the masses with a long range, fast charging and the safety of a 5-star rated platform.',
  },
  {
    id: 'mahindra-scorpio-n',
    brand: 'Mahindra', model: 'Scorpio-N', variant: 'Z8L Diesel 4x4', year: 2025,
    price: 2499000, emiStart: 41600, fuel: 'Diesel', transmission: 'Automatic', bodyType: 'SUV',
    mileage: '14.2 kmpl', seating: 7, bootSpace: '460 L', engine: '2198 cc', power: '172 bhp', torque: '400 Nm', safetyRating: 4,
    status: 'New', featured: true, published: true,
    image: 'https://images.pexels.com/photos/9550419/pexels-photo-9550419.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Napoli Black', hex: '#0d0d10' }, { name: 'Diamond White', hex: '#f4f4f4' }, { name: 'Grandeur Grey', hex: '#4a4a53' }],
    features: ['4x4 with 4WD modes', 'AdrenoX infotainment', 'Dual 12.3-inch displays', '8 airbags', 'Sunroof', 'EPB with Auto Hold'],
    pros: ['Rugged 4x4 capability', 'Powerful diesel torque', 'Commanding stance'],
    cons: ['Firm ride', 'Third row is tight'],
    variants: [
      { name: 'Z2', price: 1399000, transmission: 'Manual', fuel: 'Diesel' },
      { name: 'Z8', price: 1999000, transmission: 'Manual', fuel: 'Diesel' },
      { name: 'Z8L Diesel 4x4', price: 2499000, transmission: 'Automatic', fuel: 'Diesel' },
    ],
    description: 'The Mahindra Scorpio-N is a burly 7-seater SUV with proper 4x4 hardware, a torquey diesel engine and a cabin that feels a class above.',
  },
  {
    id: 'mahindra-thar',
    brand: 'Mahindra', model: 'Thar', variant: 'LX Diesel 4x4', year: 2025,
    price: 1599000, emiStart: 26600, fuel: 'Diesel', transmission: 'Automatic', bodyType: 'SUV',
    mileage: '15.2 kmpl', seating: 4, bootSpace: '295 L', engine: '2184 cc', power: '128 bhp', torque: '300 Nm', safetyRating: 4,
    status: 'New', featured: false, published: true,
    image: 'https://images.pexels.com/photos/8337436/pexels-photo-8337436.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Napoli Black', hex: '#0d0d10' }, { name: 'Diamond White', hex: '#f4f4f4' }, { name: 'Red Rage', hex: '#dc1f1f' }],
    features: ['4x4 with low-range', 'Lockable differential', 'Off-road modes', '7-inch infotainment', 'Roof-mounted speakers', 'Cruise control'],
    pros: ['Legendary off-roader', 'Head-turning looks', 'Convertible option'],
    cons: ['Bumpy ride on road', 'Limited boot space'],
    variants: [
      { name: 'AX', price: 1199000, transmission: 'Manual', fuel: 'Diesel' },
      { name: 'LX', price: 1399000, transmission: 'Manual', fuel: 'Diesel' },
      { name: 'LX Diesel 4x4', price: 1599000, transmission: 'Automatic', fuel: 'Diesel' },
    ],
    description: 'The Mahindra Thar is India\'s iconic off-roader, built to conquer any terrain with proper 4x4 hardware and unmistakable road presence.',
  },
  {
    id: 'toyota-innova',
    brand: 'Toyota', model: 'Innova Crysta', variant: 'ZX Diesel AT', year: 2025,
    price: 2699000, emiStart: 44900, fuel: 'Diesel', transmission: 'Automatic', bodyType: 'MUV',
    mileage: '12.5 kmpl', seating: 7, bootSpace: '300 L', engine: '2755 cc', power: '148 bhp', torque: '360 Nm', safetyRating: 5,
    status: 'New', featured: false, published: true,
    image: 'https://images.pexels.com/photos/2036544/pexels-photo-2036544.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Pearl White', hex: '#f4f4f4' }, { name: 'Attitude Black', hex: '#0d0d10' }, { name: 'Avant Garde Silver', hex: '#9a9aa3' }],
    features: ['8-inch infotainment', '7 airbags', 'Captain seats', 'Ambient lighting', 'Auto climate control', 'Reverse camera'],
    pros: ['Bulletproof reliability', 'Plush ride quality', 'Spacious cabin'],
    cons: ['Premium pricing', 'Dated infotainment'],
    variants: [
      { name: 'G', price: 1999000, transmission: 'Manual', fuel: 'Diesel' },
      { name: 'VX', price: 2399000, transmission: 'Manual', fuel: 'Diesel' },
      { name: 'ZX Diesel AT', price: 2699000, transmission: 'Automatic', fuel: 'Diesel' },
    ],
    description: 'The Toyota Innova Crysta is the benchmark for premium MPVs, offering unmatched comfort, reliability and resale value for families and fleets alike.',
  },
  {
    id: 'toyota-fortuner',
    brand: 'Toyota', model: 'Fortuner', variant: 'Legender 4x4 AT', year: 2025,
    price: 4299000, emiStart: 71600, fuel: 'Diesel', transmission: 'Automatic', bodyType: 'SUV',
    mileage: '10.0 kmpl', seating: 7, bootSpace: '296 L', engine: '2755 cc', power: '201 bhp', torque: '500 Nm', safetyRating: 5,
    status: 'New', featured: true, published: true,
    image: 'https://images.pexels.com/photos/14850138/pexels-photo-14850138.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Pearl White', hex: '#f4f4f4' }, { name: 'Attitude Black', hex: '#0d0d10' }, { name: 'Phantom Brown', hex: '#3a2e26' }],
    features: ['4x4 with low-range', '11-speaker JBL', 'Dual-zone climate', '7 airbags', '360 camera', 'Wireless charger'],
    pros: ['Dominant road presence', 'Effortless cruising', 'Strong resale'],
    cons: ['Expensive to buy', 'Bumpy at low speeds'],
    variants: [
      { name: '4x2 MT', price: 3399000, transmission: 'Manual', fuel: 'Diesel' },
      { name: '4x2 AT', price: 3699000, transmission: 'Automatic', fuel: 'Diesel' },
      { name: 'Legender 4x4 AT', price: 4299000, transmission: 'Automatic', fuel: 'Diesel' },
    ],
    description: 'The Toyota Fortuner is the aspirational full-size SUV, combining unstoppable 4x4 performance with a luxurious cabin and commanding road presence.',
  },
  {
    id: 'kia-sonet',
    brand: 'Kia', model: 'Sonet', variant: 'X-Line Diesel AT', year: 2025,
    price: 1399000, emiStart: 23300, fuel: 'Diesel', transmission: 'AMT', bodyType: 'SUV',
    mileage: '18.4 kmpl', seating: 5, bootSpace: '392 L', engine: '1493 cc', power: '114 bhp', torque: '250 Nm', safetyRating: 4,
    status: 'New', featured: false, published: true,
    image: 'https://images.pexels.com/photos/22608249/pexels-photo-22608249.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Intelligency Blue', hex: '#1e3a5f' }, { name: 'Aurora Black', hex: '#0d0d10' }, { name: 'Beige Gold', hex: '#c6c6cc' }],
    features: ['10.25-inch display', 'Bose sound system', '6 airbags', 'Sunroof', 'Wireless charging', 'Ventilated seats'],
    pros: ['Punchy diesel engine', 'Compact city-friendly size', 'Loaded features'],
    cons: ['AMT gearbox is slow', 'Rear seat is tight'],
    variants: [
      { name: 'HTE', price: 799000, transmission: 'Manual', fuel: 'Diesel' },
      { name: 'HTX', price: 1099000, transmission: 'Manual', fuel: 'Diesel' },
      { name: 'X-Line Diesel AT', price: 1399000, transmission: 'AMT', fuel: 'Diesel' },
    ],
    description: 'The Kia Sonet is a feature-packed compact SUV that brings a premium diesel engine and segment-first tech to the sub-4m segment.',
  },
  {
    id: 'kia-seltos',
    brand: 'Kia', model: 'Seltos', variant: 'X-Line Turbo DCT', year: 2025,
    price: 1899000, emiStart: 31600, fuel: 'Petrol', transmission: 'DCT', bodyType: 'SUV',
    mileage: '17.0 kmpl', seating: 5, bootSpace: '433 L', engine: '1482 cc', power: '138 bhp', torque: '242 Nm', safetyRating: 5,
    status: 'New', featured: true, published: true,
    image: 'https://images.pexels.com/photos/7290399/pexels-photo-7290399.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Aurora Black', hex: '#0d0d10' }, { name: 'Snow White Pearl', hex: '#f4f4f4' }, { name: 'Intelligency Blue', hex: '#1e3a5f' }],
    features: ['10.25-inch infotainment', 'Bose 8-speaker', 'Level 2 ADAS', 'Panoramic sunroof', '8 airbags', 'Drive modes'],
    pros: ['Punchy turbo engine', 'Premium cabin', 'Sharp styling'],
    cons: ['Firm ride', 'No diesel automatic'],
    variants: [
      { name: 'TECH', price: 1199000, transmission: 'Manual', fuel: 'Petrol' },
      { name: 'HTX+', price: 1599000, transmission: 'Manual', fuel: 'Petrol' },
      { name: 'X-Line Turbo DCT', price: 1899000, transmission: 'DCT', fuel: 'Petrol' },
    ],
    description: 'The Kia Seltos is a sharp-looking mid-size SUV with a turbocharged engine, ADAS safety tech and a cabin that feels genuinely premium.',
  },
  {
    id: 'bmw-3-series',
    brand: 'BMW', model: '3 Series Gran Limousine', variant: '330Li M Sport', year: 2025,
    price: 6299000, emiStart: 104900, fuel: 'Petrol', transmission: 'Automatic', bodyType: 'Luxury',
    mileage: '15.0 kmpl', seating: 5, bootSpace: '480 L', engine: '1998 cc', power: '255 bhp', torque: '400 Nm', safetyRating: 5,
    status: 'New', featured: true, published: true,
    image: 'https://images.pexels.com/photos/12066287/pexels-photo-12066287.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Alpine White', hex: '#f4f4f4' }, { name: 'Carbon Black', hex: '#0d0d10' }, { name: 'Mineral Grey', hex: '#4a4a53' }],
    features: ['iDrive 8.5', 'Live Cockpit Professional', 'Harman Kardon audio', 'Adaptive LED', 'Parking Assistant Plus', 'Sunroof'],
    pros: ['Driver-focused dynamics', 'Refined inline-four', 'Premium materials'],
    cons: ['Expensive maintenance', 'Firm ride in Sport mode'],
    variants: [
      { name: '320Ld', price: 4999000, transmission: 'Automatic', fuel: 'Diesel' },
      { name: '330Li Sport', price: 5699000, transmission: 'Automatic', fuel: 'Petrol' },
      { name: '330Li M Sport', price: 6299000, transmission: 'Automatic', fuel: 'Petrol' },
    ],
    description: 'The BMW 3 Series Gran Limousine is the benchmark sports sedan, blending long-wheelbase comfort with the driving dynamics BMW is known for.',
  },
  {
    id: 'bmw-x5',
    brand: 'BMW', model: 'X5', variant: 'xDrive40i M Sport', year: 2025,
    price: 9999000, emiStart: 166600, fuel: 'Petrol', transmission: 'Automatic', bodyType: 'Luxury',
    mileage: '11.2 kmpl', seating: 5, bootSpace: '650 L', engine: '2998 cc', power: '375 bhp', torque: '520 Nm', safetyRating: 5,
    status: 'New', featured: false, published: true,
    image: 'https://images.pexels.com/photos/7762700/pexels-photo-7762700.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Alpine White', hex: '#f4f4f4' }, { name: 'Carbon Black', hex: '#0d0d10' }, { name: 'Phantom Grey', hex: '#4a4a53' }],
    features: ['Curved Display', 'Bowers & Wilkins audio', 'Adaptive 2-axle air suspension', 'Laser headlights', 'Sky Lounge sunroof', 'Reversing Assistant'],
    pros: ['Effortless performance', 'Plush air suspension', 'Luxurious cabin'],
    cons: ['High running costs', 'Limited off-road clearance'],
    variants: [
      { name: 'xDrive30d', price: 8799000, transmission: 'Automatic', fuel: 'Diesel' },
      { name: 'xDrive40i SportX', price: 9399000, transmission: 'Automatic', fuel: 'Petrol' },
      { name: 'xDrive40i M Sport', price: 9999000, transmission: 'Automatic', fuel: 'Petrol' },
    ],
    description: 'The BMW X5 is the definitive luxury SUV, pairing effortless six-cylinder performance with adaptive air suspension and a beautifully finished cabin.',
  },
  {
    id: 'mercedes-c-class',
    brand: 'Mercedes-Benz', model: 'C-Class', variant: 'C 300d AMG Line', year: 2025,
    price: 6299000, emiStart: 104900, fuel: 'Diesel', transmission: 'Automatic', bodyType: 'Luxury',
    mileage: '18.5 kmpl', seating: 5, bootSpace: '455 L', engine: '1992 cc', power: '261 bhp', torque: '550 Nm', safetyRating: 5,
    status: 'New', featured: true, published: true,
    image: 'https://images.pexels.com/photos/12066299/pexels-photo-12066299.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Polar White', hex: '#f4f4f4' }, { name: 'Obsidian Black', hex: '#0d0d10' }, { name: 'Selenite Grey', hex: '#4a4a53' }],
    features: ['MBUX 11.9-inch display', 'Burmester 3D sound', 'Augmented navigation', 'Air Body Control', '360 camera', 'Wireless charging'],
    pros: ['Silky diesel engine', 'Tech-laden cabin', 'Effortless cruising'],
    cons: ['Firm AMG suspension', 'Limited rear headroom'],
    variants: [
      { name: 'C 200', price: 5499000, transmission: 'Automatic', fuel: 'Petrol' },
      { name: 'C 220d', price: 5899000, transmission: 'Automatic', fuel: 'Diesel' },
      { name: 'C 300d AMG Line', price: 6299000, transmission: 'Automatic', fuel: 'Diesel' },
    ],
    description: 'The Mercedes-Benz C-Class brings S-Class levels of technology to the executive sedan segment with a refined diesel engine and a stunning MBUX cabin.',
  },
  {
    id: 'mercedes-gle',
    brand: 'Mercedes-Benz', model: 'GLE', variant: 'GLE 400d 4MATIC', year: 2025,
    price: 9999000, emiStart: 166600, fuel: 'Diesel', transmission: 'Automatic', bodyType: 'Luxury',
    mileage: '12.8 kmpl', seating: 5, bootSpace: '825 L', engine: '2925 cc', power: '326 bhp', torque: '700 Nm', safetyRating: 5,
    status: 'New', featured: false, published: true,
    image: 'https://images.pexels.com/photos/26871073/pexels-photo-26871073.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Polar White', hex: '#f4f4f4' }, { name: 'Obsidian Black', hex: '#0d0d10' }, { name: 'Mojave Silver', hex: '#9a9aa3' }],
    features: ['MBUX Dual Display', 'Burmester sound', 'AIRMATIC suspension', 'E-Active Body Control', 'Multibeam LED', 'Driver Assistance Package'],
    pros: ['Torque-rich diesel', 'Magic-carpet ride', 'Vast cabin'],
    cons: ['Steep pricing', 'Wide footprint'],
    variants: [
      { name: 'GLE 300d', price: 8999000, transmission: 'Automatic', fuel: 'Diesel' },
      { name: 'GLE 450 4MATIC', price: 9499000, transmission: 'Automatic', fuel: 'Petrol' },
      { name: 'GLE 400d 4MATIC', price: 9999000, transmission: 'Automatic', fuel: 'Diesel' },
    ],
    description: 'The Mercedes-Benz GLE is a luxurious 7-seat-ready SUV with a torquey diesel, AIRMATIC suspension and a cabin that rivals luxury lounges.',
  },
  {
    id: 'audi-a4',
    brand: 'Audi', model: 'A4', variant: '45 TFSI Technology', year: 2025,
    price: 4699000, emiStart: 78300, fuel: 'Petrol', transmission: 'Automatic', bodyType: 'Luxury',
    mileage: '14.0 kmpl', seating: 5, bootSpace: '460 L', engine: '1984 cc', power: '241 bhp', torque: '370 Nm', safetyRating: 5,
    status: 'New', featured: false, published: true,
    image: 'https://images.pexels.com/photos/13627425/pexels-photo-13627425.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Glacier White', hex: '#f4f4f4' }, { name: 'Mythos Black', hex: '#0d0d10' }, { name: 'Navarra Blue', hex: '#1e3a5f' }],
    features: ['Virtual Cockpit Plus', 'Bang & Olufsen audio', 'Matrix LED', 'Panoramic sunroof', 'Phone box', 'Audi pre sense'],
    pros: ['Balanced ride and handling', 'Premium cabin', 'Refined engine'],
    cons: ['Less rear space than rivals', 'No diesel option'],
    variants: [
      { name: '40 TFSI Premium', price: 4299000, transmission: 'Automatic', fuel: 'Petrol' },
      { name: '40 TFSI Premium Plus', price: 4499000, transmission: 'Automatic', fuel: 'Petrol' },
      { name: '45 TFSI Technology', price: 4699000, transmission: 'Automatic', fuel: 'Petrol' },
    ],
    description: 'The Audi A4 is the understated luxury sedan, offering a refined turbo-petrol, a beautifully finished cabin and balanced driving dynamics.',
  },
  {
    id: 'audi-q3',
    brand: 'Audi', model: 'Q3', variant: '40 TFSI Premium Plus', year: 2025,
    price: 4999000, emiStart: 83300, fuel: 'Petrol', transmission: 'Automatic', bodyType: 'Luxury',
    mileage: '13.5 kmpl', seating: 5, bootSpace: '530 L', engine: '1498 cc', power: '187 bhp', torque: '250 Nm', safetyRating: 5,
    status: 'New', featured: false, published: true,
    image: 'https://images.pexels.com/photos/33172884/pexels-photo-33172884.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Glacier White', hex: '#f4f4f4' }, { name: 'Mythos Black', hex: '#0d0d10' }, { name: 'Navarra Blue', hex: '#1e3a5f' }],
    features: ['10.1-inch MMI', 'Panoramic sunroof', '8 speakers', 'Audi pre sense', 'Reverse camera', 'Wireless CarPlay'],
    pros: ['Entry luxury done right', 'Practical boot', 'Premium feel'],
    cons: ['No diesel', 'Rivals offer more power'],
    variants: [
      { name: '40 TFSI Premium', price: 4499000, transmission: 'Automatic', fuel: 'Petrol' },
      { name: '40 TFSI Premium Plus', price: 4999000, transmission: 'Automatic', fuel: 'Petrol' },
    ],
    description: 'The Audi Q3 is the gateway to the four rings, offering a premium cabin, practical boot and a refined turbo-petrol in a compact SUV footprint.',
  },
  {
    id: 'vw-polo',
    brand: 'Volkswagen', model: 'Polo', variant: 'GT 1.0 TSI', year: 2024,
    price: 949000, emiStart: 15800, fuel: 'Petrol', transmission: 'Manual', bodyType: 'Hatchback',
    mileage: '17.5 kmpl', seating: 5, bootSpace: '280 L', engine: '999 cc', power: '108 bhp', torque: '175 Nm', safetyRating: 4,
    status: 'New', featured: false, published: true,
    image: 'https://images.pexels.com/photos/16634761/pexels-photo-16634761.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Candy White', hex: '#f4f4f4' }, { name: 'Carbon Steel', hex: '#4a4a53' }, { name: 'Tornado Red', hex: '#dc1f1f' }],
    features: ['Touchscreen infotainment', 'Apple CarPlay & Android Auto', '4 airbags', 'Cruise control', 'Multi-function steering', 'Climatronic'],
    pros: ['Tank-like build quality', 'Fun turbo engine', 'Precise steering'],
    cons: ['Dated interior', 'Limited rear space'],
    variants: [
      { name: 'Trendline', price: 649000, transmission: 'Manual', fuel: 'Petrol' },
      { name: 'Comfortline', price: 799000, transmission: 'Manual', fuel: 'Petrol' },
      { name: 'GT 1.0 TSI', price: 949000, transmission: 'Manual', fuel: 'Petrol' },
    ],
    description: 'The Volkswagen Polo is the enthusiast\'s hatchback, legendary for its solid build, punchy turbo engine and German driving dynamics.',
  },
  {
    id: 'vw-tiguan',
    brand: 'Volkswagen', model: 'Tiguan', variant: '2.0 TSI Elegance', year: 2025,
    price: 3599000, emiStart: 59900, fuel: 'Petrol', transmission: 'Automatic', bodyType: 'SUV',
    mileage: '12.6 kmpl', seating: 5, bootSpace: '615 L', engine: '1984 cc', power: '187 bhp', torque: '320 Nm', safetyRating: 5,
    status: 'New', featured: false, published: true,
    image: 'https://images.pexels.com/photos/16646415/pexels-photo-16646415.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Pure White', hex: '#f4f4f4' }, { name: 'Carbon Steel Grey', hex: '#4a4a53' }, { name: 'Indium Grey', hex: '#34343c' }],
    features: ['Digital Cockpit Pro', '8-inch Discover Pro', 'Vienna leather seats', 'Panoramic sunroof', '9 airbags', 'IQ Drive'],
    pros: ['Premium European build', 'Spacious cabin', 'Refined engine'],
    cons: ['Pricey for the segment', 'Limited variants'],
    variants: [
      { name: '2.0 TSI Elegance', price: 3599000, transmission: 'Automatic', fuel: 'Petrol' },
      { name: '2.0 TSI R-Line', price: 3899000, transmission: 'Automatic', fuel: 'Petrol' },
    ],
    description: 'The Volkswagen Tiguan is a premium 5-seat SUV that brings European build quality, a refined turbo-petrol and a cavernous boot to the segment.',
  },
  {
    id: 'hyundai-verna',
    brand: 'Hyundai', model: 'Verna', variant: 'SX(O) Turbo DCT', year: 2025,
    price: 1699000, emiStart: 28300, fuel: 'Petrol', transmission: 'DCT', bodyType: 'Sedan',
    mileage: '18.0 kmpl', seating: 5, bootSpace: '528 L', engine: '1482 cc', power: '157 bhp', torque: '253 Nm', safetyRating: 5,
    status: 'New', featured: false, published: true,
    image: 'https://images.pexels.com/photos/12353734/pexels-photo-12353734.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Phantom Black', hex: '#0d0d10' }, { name: 'Polar White', hex: '#f4f4f4' }, { name: 'Titan Grey', hex: '#4a4a53' }],
    features: ['10.25-inch cluster', 'Bose 8-speaker', '6 airbags', 'Level 2 ADAS', 'Ventilated seats', 'Sunroof'],
    pros: ['Striking design', 'Punchy turbo engine', 'Loaded with safety'],
    cons: ['Low ground clearance', 'Rear headroom for tall passengers'],
    variants: [
      { name: 'EX', price: 1099000, transmission: 'Manual', fuel: 'Petrol' },
      { name: 'SX', price: 1299000, transmission: 'Manual', fuel: 'Petrol' },
      { name: 'SX(O) Turbo DCT', price: 1699000, transmission: 'DCT', fuel: 'Petrol' },
    ],
    description: 'The Hyundai Verna is a bold mid-size sedan with a striking design, turbocharged performance and a full suite of Level 2 ADAS safety features.',
  },
  {
    id: 'maruti-dzire',
    brand: 'Maruti Suzuki', model: 'Dzire', variant: 'ZXi+', year: 2025,
    price: 849000, emiStart: 14100, fuel: 'Petrol', transmission: 'AMT', bodyType: 'Sedan',
    mileage: '22.6 kmpl', seating: 5, bootSpace: '378 L', engine: '1197 cc', power: '89 bhp', torque: '113 Nm', safetyRating: 4,
    status: 'New', featured: false, published: true,
    image: 'https://images.pexels.com/photos/13936547/pexels-photo-13936547.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Pearl Arctic White', hex: '#f4f4f4' }, { name: 'Magma Red', hex: '#b81515' }, { name: 'Midnight Blue', hex: '#1e2a4a' }],
    features: ['7-inch SmartPlay', 'Apple CarPlay & Android Auto', '6 airbags', 'Reverse camera', 'Keyless entry', 'Cruise control'],
    pros: ['Best-in-class mileage', 'Spacious boot', 'Refined engine'],
    cons: ['AMT can be jerky', 'No diesel option'],
    variants: [
      { name: 'LXi', price: 649000, transmission: 'Manual', fuel: 'Petrol' },
      { name: 'VXi', price: 749000, transmission: 'Manual', fuel: 'Petrol' },
      { name: 'ZXi+', price: 849000, transmission: 'AMT', fuel: 'Petrol' },
    ],
    description: 'The Maruti Suzuki Dzire is India\'s best-selling compact sedan, offering class-leading fuel economy, a spacious boot and a refined petrol engine.',
  },
  {
    id: 'tata-harrier',
    brand: 'Tata', model: 'Harrier', variant: 'Fearless+ Dark AT', year: 2025,
    price: 2499000, emiStart: 41600, fuel: 'Diesel', transmission: 'Automatic', bodyType: 'SUV',
    mileage: '15.0 kmpl', seating: 5, bootSpace: '425 L', engine: '1956 cc', power: '167 bhp', torque: '350 Nm', safetyRating: 5,
    status: 'New', featured: false, published: true,
    image: 'https://images.pexels.com/photos/37025272/pexels-photo-37025272.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Oberon Black', hex: '#0d0d10' }, { name: 'Cosmic Gold', hex: '#8a7a4a' }, { name: 'Pristine White', hex: '#f4f4f4' }],
    features: ['12.3-inch infotainment', 'JBL 9-speaker', '6 airbags', 'Level 2 ADAS', 'Powered tailgate', 'Ventilated seats'],
    pros: ['5-star safety', 'Commanding stance', 'Refined diesel'],
    cons: ['No petrol option', 'Wide turning radius'],
    variants: [
      { name: 'Smart', price: 1599000, transmission: 'Manual', fuel: 'Diesel' },
      { name: 'Adventure', price: 1999000, transmission: 'Manual', fuel: 'Diesel' },
      { name: 'Fearless+ Dark AT', price: 2499000, transmission: 'Automatic', fuel: 'Diesel' },
    ],
    description: 'The Tata Harrier is a 5-star safe mid-size SUV with a commanding stance, a refined diesel engine and a cabin loaded with ADAS safety tech.',
  },
  {
    id: 'used-creta-2022',
    brand: 'Hyundai', model: 'Creta', variant: 'SX Diesel', year: 2022,
    price: 1149000, emiStart: 19100, fuel: 'Diesel', transmission: 'Manual', bodyType: 'SUV',
    mileage: '21.0 kmpl', seating: 5, bootSpace: '433 L', engine: '1493 cc', power: '114 bhp', torque: '250 Nm', safetyRating: 5,
    status: 'Used', featured: false, published: true,
    image: 'https://images.pexels.com/photos/13767773/pexels-photo-13767773.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Polar White', hex: '#f4f4f4' }, { name: 'Phantom Black', hex: '#0d0d10' }],
    features: ['8-inch touchscreen', '6 airbags', 'Reverse camera', 'Cruise control', 'Climate control', 'Wireless charging'],
    pros: ['Well-priced used buy', 'Frugal diesel', 'Spacious cabin'],
    cons: ['Higher mileage', 'No warranty'],
    variants: [
      { name: 'SX Diesel', price: 1149000, transmission: 'Manual', fuel: 'Diesel' },
    ],
    description: 'A well-maintained 2022 Hyundai Creta diesel that delivers SUV practicality and fuel efficiency at an attractive used-car price.',
  },
  {
    id: 'used-city-2021',
    brand: 'Honda', model: 'City', variant: 'ZX CVT', year: 2021,
    price: 1199000, emiStart: 19900, fuel: 'Petrol', transmission: 'Automatic', bodyType: 'Sedan',
    mileage: '18.4 kmpl', seating: 5, bootSpace: '506 L', engine: '1498 cc', power: '119 bhp', torque: '145 Nm', safetyRating: 5,
    status: 'Used', featured: false, published: true,
    image: 'https://images.pexels.com/photos/18029637/pexels-photo-18029637.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    colors: [{ name: 'Platinum White', hex: '#f4f4f4' }, { name: 'Modern Steel', hex: '#4a4a53' }],
    features: ['8-inch touchscreen', '6 airbags', 'Honda Sensing', 'Sunroof', 'Wireless charging', 'Leather seats'],
    pros: ['Refined i-VTEC engine', 'Spacious rear seat', 'Reliable sedan'],
    cons: ['No diesel', 'Low ground clearance'],
    variants: [
      { name: 'ZX CVT', price: 1199000, transmission: 'Automatic', fuel: 'Petrol' },
    ],
    description: 'A 2021 Honda City CVT with Honda Sensing safety, a refined petrol engine and the legroom that makes it the segment\'s comfort king.',
  },
];

export const CARS: Car[] = seeds.map((s, i) => buildCar(s, i));

export const ENQUIRIES: Enquiry[] = [
  { id: 'e1', name: 'Rahul Mehta', phone: '+91 98200 11223', email: 'rahul.mehta@example.com', car: 'Hyundai Creta', message: 'Interested in a test drive this weekend.', date: '2025-08-18', status: 'New' },
  { id: 'e2', name: 'Priya Sharma', phone: '+91 99300 44556', email: 'priya.s@example.com', car: 'Tata Nexon EV', message: 'What are the charging options at home?', date: '2025-08-16', status: 'Contacted' },
  { id: 'e3', name: 'Aman Verma', phone: '+91 98765 33221', email: 'aman.v@example.com', car: 'BMW 3 Series', message: 'Looking for finance options for the 330Li.', date: '2025-08-14', status: 'Converted' },
  { id: 'e4', name: 'Sneha Iyer', phone: '+91 90090 88776', email: 'sneha.iyer@example.com', car: 'Kia Seltos', message: 'Need a brochure and on-road price for Mumbai.', date: '2025-08-10', status: 'Closed' },
  { id: 'e5', name: 'Vikram Nair', phone: '+91 91234 56780', email: 'vikram.nair@example.com', car: 'Mahindra Scorpio-N', message: 'Availability for the Z8L 4x4 in Kerala?', date: '2025-08-08', status: 'Contacted' },
];

export const TEST_DRIVES: TestDrive[] = [
  { id: 't1', name: 'Rahul Mehta', phone: '+91 98200 11223', email: 'rahul.mehta@example.com', car: 'Hyundai Creta', date: '2025-08-22', time: '11:00 AM', city: 'Mumbai', message: 'Prefer a petrol variant.', status: 'Pending' },
  { id: 't2', name: 'Priya Sharma', phone: '+91 99300 44556', email: 'priya.s@example.com', car: 'Tata Nexon EV', date: '2025-08-21', time: '04:00 PM', city: 'Bengaluru', message: 'Want to understand home charging.', status: 'Confirmed' },
  { id: 't3', name: 'Aman Verma', phone: '+91 98765 33221', email: 'aman.v@example.com', car: 'BMW 3 Series', date: '2025-08-19', time: '10:30 AM', city: 'Delhi', message: 'Looking at the 330Li M Sport.', status: 'Completed' },
  { id: 't4', name: 'Sneha Iyer', phone: '+91 90090 88776', email: 'sneha.iyer@example.com', car: 'Kia Seltos', date: '2025-08-25', time: '02:00 PM', city: 'Pune', message: 'X-Line Turbo DCT please.', status: 'Pending' },
];

export const CUSTOMERS: Customer[] = [
  { id: 'c1', name: 'Rahul Mehta', email: 'rahul.mehta@example.com', phone: '+91 98200 11223', enquiries: 1, testDrives: 1, registeredOn: '2025-08-18' },
  { id: 'c2', name: 'Priya Sharma', email: 'priya.s@example.com', phone: '+91 99300 44556', enquiries: 1, testDrives: 1, registeredOn: '2025-08-16' },
  { id: 'c3', name: 'Aman Verma', email: 'aman.v@example.com', phone: '+91 98765 33221', enquiries: 1, testDrives: 1, registeredOn: '2025-08-14' },
  { id: 'c4', name: 'Sneha Iyer', email: 'sneha.iyer@example.com', phone: '+91 90090 88776', enquiries: 1, testDrives: 1, registeredOn: '2025-08-10' },
  { id: 'c5', name: 'Vikram Nair', email: 'vikram.nair@example.com', phone: '+91 91234 56780', enquiries: 1, testDrives: 0, registeredOn: '2025-08-08' },
];

export const HOME_REVIEWS = [
  { id: 'h1', name: 'Arjun Kapoor', location: 'Mumbai', rating: 5, text: 'Auto Empire helped me shortlist three SUVs in 10 minutes. The compare tool made the decision obvious.' },
  { id: 'h2', name: 'Divya Menon', location: 'Bengaluru', rating: 5, text: 'Booked a test drive for the Nexon EV and the team showed up exactly on time. Smooth experience.' },
  { id: 'h3', name: 'Karthik Raman', location: 'Chennai', rating: 4, text: 'The detailed specs and honest pros and cons saved me from a bad purchase. Highly recommend.' },
  { id: 'h4', name: 'Nisha Agarwal', location: 'Delhi', rating: 5, text: 'Found a used Creta within my budget in two days. The wishlist feature kept my shortlist organised.' },
];

export function formatPrice(price: number): string {
  if (price >= 10000000) return `₹${(price / 10000000).toFixed(2)} Cr`;
  return `₹${(price / 100000).toFixed(2)} Lakh`;
}

export function formatEmi(price: number): string {
  return `₹${Math.round(price / 60).toLocaleString('en-IN')}/mo`;
}
