import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useNavigate,useParams,Link,Routes,Route} from 'react-router-dom';
import {Client,TablesDB,Storage,ID,Query,InputFile} from '@appwrite.io/sdk';
import './style.css';

const ENDPOINT='https://fra.cloud.appwrite.io/v1',PROJECT_ID='6a7ad09c002b3c4f35d2',DATABASE_ID='6a7ad20d00262e017803',TABLE_ID='cars',BUCKET_ID='car-photos';
const client=new Client().setEndpoint(ENDPOINT).setProject(PROJECT_ID); const db=new TablesDB(client); const storage=new Storage(client);
const fallback='https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80';
const parse=v=>Array.isArray(v)?v:(typeof v==='string'?(()=>{try{let x=JSON.parse(v);return Array.isArray(x)?x:x?[x]:[]}catch{return v?[v]:[]}})():[]);
const image=id=>!id?fallback:String(id).startsWith('http')?id:storage.getFileView(BUCKET_ID,id).toString();
async function cars(){const r=await db.listRows({databaseId:DATABASE_ID,tableId:TABLE_ID,queries:[Query.limit(100)]});return r.rows||[]}
function Header(){const [menu,setMenu]=useState(false);return <header><Link to="/" className="logo"><span>🚗</span> Auto<span>Empire</span></Link><nav className={menu?'open':''}><Link to="/cars">Cars</Link><Link to="/brands">Brands</Link><Link to="/compare">Compare</Link><Link to="/wishlist">Wishlist</Link><Link to="/admin">Admin</Link></nav><button className="hamb" onClick={()=>setMenu(!menu)}>☰</button></header>}
function Card({c,onCompare}){let p=parse(c.photos);return <article className="card"><div className="photo"><img src={image(p[0])}/>{c.isNew&&<b>New</b>}</div><div className="ci"><small>{c.brand||'—'}</small><h3>{c.model||c.name||'Premium Car'}</h3><strong>₹{Number(c.price||0).toLocaleString('en-IN')}</strong><p>⛽ {c.fuel||'—'}　⚙ {c.transmission||'—'}　📅 {c.year||'—'}</p><div className="actions"><Link className="primary" to={'/car/'+c.$id}>◉ View Details</Link><button onClick={()=>onCompare?.(c)}>⇄ Compare</button></div></div></article>}
function Home(){const[c,setC]=useState([]);useEffect(()=>{cars().then(setC).catch(console.error)},[]);return <><Header/><main><section className="hero"><div><label>AUTO EMPIRE</label><h1>Find Your<br/>Perfect Car</h1><p>Explore new & used cars from trusted brands across India.</p><Link className="primary big" to="/cars">Explore Cars →</Link></div></section><section className="searchbox"><h3>Find your car</h3><div className="searchrow"><input placeholder="Search brand or model"/><select><option>Any Price</option><option>Under ₹10 Lakh</option><option>₹10–20 Lakh</option><option>Above ₹20 Lakh</option></select><Link className="primary" to="/cars">⌕ Search Cars</Link></div></section><h2>Popular Brands</h2><p className="muted">Explore cars from India's most-loved automakers.</p><div className="brands">{['Tata','Mahindra','Toyota','Kia','BMW','Mercedes-Benz','Audi','Volkswagen'].map(x=><Link to={'/cars?brand='+x} key={x}><span>🚘</span><b>{x}</b><small>Explore models</small></Link>)}</div><h2>Latest Cars</h2><div className="grid">{c.slice(0,6).map(x=><Card c={x} key={x.$id}/>)}</div></main></>}
function Cars(){const[c,setC]=useState([]),[q,setQ]=useState('');useEffect(()=>{cars().then(setC)},[]);let list=useMemo(()=>c.filter(x=>`${x.brand} ${x.model} ${x.name}`.toLowerCase().includes(q.toLowerCase())),[c,q]);let compare=x=>{let a=JSON.parse(localStorage.getItem('compare')||'[]');if(!a.includes(x.$id)&&a.length<4)localStorage.setItem('compare',JSON.stringify([...a,x.$id]));alert('Added to compare');};return <><Header/><main><h1>Explore Cars</h1><p className="muted">Browse cars matching your filters.</p><div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search cars..."/><select><option>Popular</option><option>Price: Low to High</option><option>Newest</option></select></div><div className="grid">{list.map(x=><Card c={x} onCompare={compare} key={x.$id}/>)}</div></main></>}
function Detail(){const{id}=useParams(),[c,setC]=useState();useEffect(()=>{db.getRow({databaseId:DATABASE_ID,tableId:TABLE_ID,rowId:id}).then(setC)},[id]);if(!c)return <><Header/><main>Loading...</main></>;let ps=parse(c.photos);return <><Header/><main className="detail"><img className="detailimg" src={image(ps[0])}/><div><label>{c.brand}</label><h1>{c.model||c.name}</h1><h2>₹{Number(c.price||0).toLocaleString('en-IN')}</h2><div className="specs"><span>⛽ {c.fuel||'—'}</span><span>⚙ {c.transmission||'—'}</span><span>📅 {c.year||'—'}</span><span>🛣 {c.km||'—'} km</span></div><p>{c.description||'Premium vehicle listed by Auto Empire.'}</p><Link className="primary big" to="/test-drive">Book Test Drive</Link></div></main></>}
function Brands(){return <><Header/><main><label>BROWSE BY MAKE</label><h1>Popular Brands</h1><div className="brands">{['Tata','Mahindra','Toyota','Kia','BMW','Mercedes-Benz','Audi','Volkswagen'].map(x=><Link to={'/cars'} key={x}><span>🚘</span><b>{x}</b><small>Models</small></Link>)}</div></main></>}
function Compare(){const[c,setC]=useState([]);useEffect(()=>{let ids=JSON.parse(localStorage.getItem('compare')||'[]');cars().then(a=>setC(a.filter(x=>ids.includes(x.$id))))},[]);return <><Header/><main><label>COMPARE</label><h1>Compare Cars Side by Side</h1><p className="muted">Stack up to four cars against each other on price, engine, mileage and features.</p>{!c.length?<div className="empty">You currently have 0 cars in your compare list.<Link className="primary" to="/cars">Open Cars →</Link></div>:<div className="compare">{c.map(x=><div key={x.$id}><img src={image(parse(x.photos)[0])}/><h3>{x.brand} {x.model}</h3><b>₹{Number(x.price||0).toLocaleString('en-IN')}</b><p>Year: {x.year}<br/>Fuel: {x.fuel}<br/>Transmission: {x.transmission}<br/>KM: {x.km}</p></div>)}</div>}</main></>}
function Wishlist(){let ids=JSON.parse(localStorage.getItem('wishlist')||'[]');return <><Header/><main><h1>Wishlist</h1><p className="muted">Saved cars are stored on this device.</p><div className="empty">{ids.length?`${ids.length} saved car(s). Open Cars to manage them.`:'No cars in your wishlist yet.'}<Link className="primary" to="/cars">Browse Cars →</Link></div></main></>}
function Test(){return <><Header/><main><h1>Book a Test Drive</h1><p className="muted">Send your request to Auto Empire.</p><form className="form" onSubmit={e=>{e.preventDefault();alert('Test drive request submitted');e.target.reset()}}><input required placeholder="Full Name"/><input required placeholder="Phone Number"/><input type="email" placeholder="Email"/><input type="date"/><textarea placeholder="Preferred car / message"/><button className="primary">Submit Request</button></form></main></>}
function Admin(){const[c,setC]=useState([]),[file,setFile]=useState([]),[f,setF]=useState({brand:'',model:'',price:'',year:'',fuel:'Petrol',transmission:'Manual',km:'',location:'India',description:''}),[msg,setMsg]=useState('');const load=()=>cars().then(setC);useEffect(()=>{load()},[]);async function add(e){e.preventDefault();setMsg('Uploading photos and saving car...');try{let ids=[];for(const x of file){let r=await storage.createFile({bucketId:BUCKET_ID,fileId:ID.unique(),file:InputFile.fromFile(x)});ids.push(r.$id)}await db.createRow({databaseId:DATABASE_ID,tableId:TABLE_ID,rowId:ID.unique(),data:{...f,price:Number(f.price),year:Number(f.year),km:Number(f.km),photos:JSON.stringify(ids),isPublished:true,isFeatured:false}});setMsg('Car uploaded successfully.');setF({brand:'',model:'',price:'',year:'',fuel:'Petrol',transmission:'Manual',km:'',location:'India',description:''});setFile([]);load()}catch(e){setMsg('Error: '+e.message)}}async function del(id){if(confirm('Delete this car?')){await db.deleteRow({databaseId:DATABASE_ID,tableId:TABLE_ID,rowId:id});load()}}return <><Header/><main><div className="adminhead"><div><label>ADMIN PANEL</label><h1>Auto Empire Dashboard</h1></div><b>{c.length} Cars</b></div><div className="stats"><div><b>{c.length}</b><small>Total Cars</small></div><div><b>{c.filter(x=>x.isPublished).length}</b><small>Published</small></div><div><b>{c.filter(x=>x.isFeatured).length}</b><small>Featured</small></div></div><section className="panel"><h2>Add New Car</h2><form className="form" onSubmit={add}>{['brand','model','price','year','km','location'].map(k=><input required key={k} placeholder={k} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>) }<select value={f.fuel} onChange={e=>setF({...f,fuel:e.target.value})}><option>Petrol</option><option>Diesel</option><option>Electric</option><option>CNG</option></select><select value={f.transmission} onChange={e=>setF({...f,transmission:e.target.value})}><option>Manual</option><option>Automatic</option></select><textarea placeholder="Description" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><input type="file" accept="image/*" multiple onChange={e=>setFile([...e.target.files])}/><button className="primary">Upload Car</button>{msg&&<p>{msg}</p>}</form></section><section className="panel"><h2>Car Management</h2>{c.map(x=><div className="adminrow" key={x.$id}><span><b>{x.brand} {x.model}</b><small>₹{Number(x.price||0).toLocaleString('en-IN')}</small></span><button onClick={()=>del(x.$id)}>Delete</button></div>)}</section></main></>}
function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/cars" element={<Cars/>}/><Route path="/brands" element={<Brands/>}/><Route path="/car/:id" element={<Detail/>}/><Route path="/compare" element={<Compare/>}/><Route path="/wishlist" element={<Wishlist/>}/><Route path="/test-drive" element={<Test/>}/><Route path="/admin" element={<Admin/>}/></Routes>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
